services:
  postgres_db:
    image: postgres:15
    container_name: monitoring_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: monitoring_website123
      POSTGRES_DB: monitoring_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d monitoring_db" ]
      interval: 3s
      timeout: 3s
      retries: 5


  redis:
    image: redis:7.4-alpine
    container_name: monitoring_redis
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    container_name: monitoring_app
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env


volumes:
  postgres_data: